#!/usr/bin/python3
"""
Minimal Example
===============
Generating a square wordcloud from the US constitution using default arguments.
"""

import sys
import os

from os import path
from wordcloud import WordCloud

fn = ""
if len(sys.argv)>1:
  fn = sys.argv[1]

ofn = ""
if len(sys.argv)>2:
  ofn = sys.argv[2]

# get data directory (using getcwd() is needed to support running example in generated IPython notebook)
d = path.dirname(__file__) if "__file__" in locals() else os.getcwd()

# Read the whole text.
#text = open(path.join(d, 'constitution.txt')).read()
text = open(path.join(d, fn)).read()

# Generate a word cloud image
wordcloud = WordCloud(collocations=False, width=800, height=600).generate(text)

# Display the generated image:
# the matplotlib way:
import matplotlib.pyplot as plt

if ofn=="":
  print("??")
  plt.imshow(wordcloud, interpolation='bilinear')
  plt.axis("off")
  plt.show()
else:
  plt.imshow(wordcloud, interpolation='bilinear')
  plt.axis("off")
  plt.savefig(ofn)

# lower max_font_size
#wordcloud = WordCloud(max_font_size=40, collocations=False).generate(text)
#plt.figure()
#plt.imshow(wordcloud, interpolation="bilinear")
#plt.axis("off")
#plt.show()
