#!/bin/bash

infn="$1"
if [[ "$infn" == "" ]] ; then infn=/dev/stdin ; fi

tmp0=`mktemp`
tmp1=`mktemp`
tmp2=`mktemp`

cat $infn | tr '[:upper:]' '[:lower:]' | tr -d '[:punct:]' | sed 's/,//' | sed G | tr ' ' '\n' > $tmp0
tail -n+2 $tmp0 > $tmp1
tail -n+2 $tmp1 > $tmp2
paste -d ',' $tmp0 $tmp1 $tmp2 | \
  grep -v -e "^," | \
  grep -v -e ",$" | \
  grep -v -e ",," | \
  sort

rm -f $tmp0 $tmp1 $tmp2
